# Generated by Django 4.1 on 2022-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='weather',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
